export const FETCHING_TIME='FETCHING_TIME';
export const FETCHING_FAILED='FETCHING_FAILED';

export const ADD_ERROR='ADD_ERROR';
export const CLEAR_ERROR='CLEAR_ERROR';

export const AUTH_ATTEMPING = 'AUTH_ATTEMPING' ;
export const AUTH_SUCCESS = 'AUTH_SUCCESS' ;
export const AUTH_FAILED = 'AUTH_FAILED' ;
export const UESR_LOGOUT='UESR_LOGOUT';
export const USER_ADDED = 'USER_ADDED';
export const PROFILE_GETTING ='PROFILE_GETTING';

export const CASE_ADDED='CASE_ADDED';
export const CASE_UPDATED='CASE_UPDATED';
export const CASE_DELETED='CASE_DELETED';
export const CASES_FETCHING_SUCCESS='CASES_FETCHING_SUCCESS';

export const INETRNSHIP_ADDED='INETRNSHIP_ADDED';
export const INETRNSHIP_UPDATED='INETRNSHIP_UPDATED';
export const INETRNSHIP_DELETED='INETRNSHIP_DELETED';
export const INTERNSHIPS_FETCHING_SUCCESS='INTERNSHIPS_FETCHING_SUCCESS';

export const APPLY='APPLY';
export const APPLICATION_DELETED='APPLICATION_DELETED';
export const APPLICATIONS_FETCHING_SUCCESS='APPLICATION_DELETED';
export const APPLICATION_UPDATED='APPLICATION_UPDATED';

export const TIME_ADDED='TIME_ADDED';
export const TIME_DELETED='TIME_DELETED';
export const TIMES_FETCHING_SUCCESS='TIMES_FETCHING_SUCCESS';

export const BOOKED='BOOKED';
export const BOOK_DELETED='BOOK_DELETED';
export const BOOKS_FETCHING_SUCCESS='BOOKS_FETCHING_SUCCESS';
export const BOOK_UPDATED='BOOK_UPDATED';

export const RATE_ADDED='RATE_ADDED';
export const RATES_FETCHING_SUCCESS='RATES_FETCHING_SUCCESS';


export const TASK_ADDED='TASK_ADDED';
export const TASK_DELETED='TASK_DELETED';
export const TASK_UPDATED='TASK_UPDATED';
export const TASKS_FETCHING_SUCCESS='TASKS_FETCHING_SUCCESS';

export const LAWYERS_FETCHING_SUCCESS='LAWYERS_FETCHING_SUCCESS';
export const LAWYER_GETTING_SUCCESS='LAWYER_GETTING_SUCCESS';

export const NOTIFICATIONS_FETCHING_SUCCESS='NOTIFICATIONS_FETCHING_SUCCESS';
export const NOTIFICATIONS_OPNED='NOTIFICATIONS_OPNED';

export const ADD_MESSAGE='ADD_MESSAGE';
export const CLEAR_MESSAGE='CLEAR_MESSAGE';


