export const FETCHING_TIME='FETCHING_TIME';
export const FETCHING_FAILED='FETCHING_FAILED';

export const ADD_ERROR='ADD_ERROR';
export const CLEAR_ERROR='CLEAR_ERROR';

export const AUTH_ATTEMPING = 'AUTH_ATTEMPING' ;
export const AUTH_SUCCESS = 'AUTH_SUCCESS' ;
export const AUTH_FAILED = 'AUTH_FAILED' ;
export const UESR_LOGOUT='UESR_LOGOUT';
export const USER_ADDED = 'USER_ADDED';
export const PROFILE_GETTING ='PROFILE_GETTING';

export const CASE_ADDED='CASE_ADDED';
export const CASE_UPDATED='CASE_UPDATED';
export const CASE_DELETED='CASE_DELETED';
export const CASES_FETCHING_SUCCESS='CASES_FETCHING_SUCCESS';
export const CASE_GETTING_SUCCESS='CASE_GETTING_SUCCESS';
export const CASES_OWNER_FETCHING_SUCCESS='CASES_OWNER_FETCHING_SUCCESS';
export const CASE_OWNER_UPDATED='CASE_OWNER_UPDATED';

export const INETRNSHIP_ADDED='INETRNSHIP_ADDED';
export const INETRNSHIP_UPDATED='INETRNSHIP_UPDATED';
export const INETRNSHIP_DELETED='INETRNSHIP_DELETED';
export const INTERNSHIPS_FETCHING_SUCCESS='INTERNSHIPS_FETCHING_SUCCESS';

export const APPLY='APPLY';
export const APPLICATION_DELETED='APPLICATION_DELETED';
export const APPLICATIONS_FETCHING_SUCCESS='APPLICATIONS_FETCHING_SUCCESS';
export const APPLICATION_UPDATED='APPLICATION_UPDATED';
export const APPLICATION_REJECTED='APPLICATION_REJECTED';
export const APPLICATION_ACCEPTED='APPLICATION_ACCEPTED';

export const TIME_ADDED='TIME_ADDED';
export const TIME_DELETED='TIME_DELETED';
export const TIMES_FETCHING_SUCCESS='TIMES_FETCHING_SUCCESS';

export const BOOKED='BOOKED';
export const BOOK_DELETED='BOOK_DELETED';
export const BOOKS_FETCHING_SUCCESS='BOOKS_FETCHING_SUCCESS';
export const BOOK_UPDATED='BOOK_UPDATED';

export const RATE_ADDED='RATE_ADDED';
export const RATES_FETCHING_SUCCESS='RATES_FETCHING_SUCCESS';
export const RATEING_GETTING_SUCCESS ='RATEING_FETCHING_SUCCESS';


export const TASK_ADDED='TASK_ADDED';
export const TASK_DELETED='TASK_DELETED';
export const TASK_UPDATED='TASK_UPDATED';
export const TASKS_FETCHING_SUCCESS='TASKS_FETCHING_SUCCESS';

export const LAWYERS_FETCHING_SUCCESS='LAWYERS_FETCHING_SUCCESS';
export const LAWYER_GETTING_SUCCESS='LAWYER_GETTING_SUCCESS';
export const INIT_LAWYER='INIT_LAWYER';

export const ADD_MESSAGE='ADD_MESSAGE';
export const CLEAR_MESSAGE='CLEAR_MESSAGE';

export const NEW_OFFICE_GETTING_SUCCESS ="NEW_OFFICE_GETTING_SUCCESS";
export const OFFICE_GETTING_SUCCESS="OFFICE_GETTING_SUCCESS";
export const MY_OFFICE_GETTING_SUCCESS='MY_OFFICE_GETTING_SUCCESS'

export const LAWYER_NOTIFICATIONS_FETCHING_SUCCESS='LAWYER_NOTIFICATIONS_FETCHING_SUCCESS';
export const STUDENT_NOTIFICATIONS_FETCHING_SUCCESS='STUDENT_NOTIFICATIONS_FETCHING_SUCCESS';
export const BOOK_NOTIFICATIONS_OPNED='BOOK_NOTIFICATIONS_OPNED';
export const APP_NOTIFICATIONS_OPNED='APP_NOTIFICATIONS_OPNED';
export const TASK_NOTIFICATIONS_OPNED='TASK_NOTIFICATIONS_OPNED';
export const STUDENT_APP_NOTIFICATIONS_OPNED='STUDENT_NOTIFICATIONS_OPNED';
export const STUDENT_TASK_NOTIFICATIONS_OPNED='STUDENT_TASK_NOTIFICATIONS_OPNED';